#!/bin/bash
# 🏗️ Repo Builder Bot
# Auto-creates repos, scaffolds projects, manages templates
# Works online (scheduled) and offline (triggered locally)

set -euo pipefail
source "${GITHUB_WORKSPACE:-.}/shared/utils.sh"

BOT_NAME="repo-builder"
REPORT="repo-builder-report.md"
TEMPLATES_DIR="${TEMPLATES_DIR:-.github/project-templates}"

log INFO "🏗️ Repo Builder starting..."

# ═══════════════════════════════════════════════════════
# Project Templates
# ═══════════════════════════════════════════════════════

create_template_index() {
  mkdir -p "$TEMPLATES_DIR"

  cat > "$TEMPLATES_DIR/index.json" << 'EOF'
{
  "templates": [
    {
      "id": "node-api",
      "name": "Node.js REST API",
      "description": "Express.js API with middleware, auth, database",
      "tech": ["node", "express", "mongodb"],
      "files": ["src/", "package.json", "README.md", "Dockerfile"]
    },
    {
      "id": "react-app",
      "name": "React Application",
      "description": "React SPA with routing, state management",
      "tech": ["react", "vite", "tailwind"],
      "files": ["src/", "public/", "package.json", "README.md"]
    },
    {
      "id": "static-site",
      "name": "Static Website",
      "description": "HTML/CSS/JS static site with GitHub Pages",
      "tech": ["html", "css", "javascript"],
      "files": ["index.html", "style.css", "script.js", "README.md"]
    },
    {
      "id": "python-api",
      "name": "Python FastAPI",
      "description": "FastAPI with Pydantic, async support",
      "tech": ["python", "fastapi", "uvicorn"],
      "files": ["main.py", "requirements.txt", "README.md", "Dockerfile"]
    },
    {
      "id": "ai-chatbot",
      "name": "AI Chatbot",
      "description": "Multi-provider AI chatbot with free API support",
      "tech": ["node", "express", "openai-compatible"],
      "files": ["src/", "package.json", "README.md", ".env.example"]
    },
    {
      "id": "saas-starter",
      "name": "SaaS Starter",
      "description": "Full SaaS with auth, billing, dashboard",
      "tech": ["nextjs", "supabase", "stripe"],
      "files": ["src/", "package.json", "README.md", ".env.example"]
    },
    {
      "id": "cli-tool",
      "name": "CLI Tool",
      "description": "Command line tool with args, config, help",
      "tech": ["node", "commander"],
      "files": ["bin/", "src/", "package.json", "README.md"]
    },
    {
      "id": "discord-bot",
      "name": "Discord Bot",
      "description": "Discord.js bot with commands, events",
      "tech": ["node", "discord.js"],
      "files": ["src/", "package.json", "README.md", ".env.example"]
    },
    {
      "id": "telegram-bot",
      "name": "Telegram Bot",
      "description": "Telegram bot with commands, inline keyboards",
      "tech": ["node", "telegraf"],
      "files": ["src/", "package.json", "README.md", ".env.example"]
    },
    {
      "id": "chrome-extension",
      "name": "Chrome Extension",
      "description": "Manifest V3 Chrome extension",
      "tech": ["javascript", "html", "css"],
      "files": ["manifest.json", "background.js", "popup/", "content.js"]
    },
    {
      "id": "api-wrapper",
      "name": "API Wrapper Library",
      "description": "npm package wrapping an external API",
      "tech": ["node", "typescript"],
      "files": ["src/", "test/", "package.json", "README.md", "tsconfig.json"]
    },
    {
      "id": "automation-tool",
      "name": "Automation Tool",
      "description": "GitHub Actions + scripts for automation",
      "tech": ["bash", "github-actions"],
      "files": [".github/workflows/", "scripts/", "README.md"]
    }
  ]
}
EOF
  log INFO "Template index created with 12 templates"
}

# ═══════════════════════════════════════════════════════
# Generate Project from Template
# ═══════════════════════════════════════════════════════
scaffold_project() {
  local template_id="$1"
  local project_name="$2"
  local description="${3:-Auto-generated by Repo Builder}"

  log INFO "Scaffolding: $project_name from template $template_id"

  mkdir -p "$project_name"
  cd "$project_name"

  case "$template_id" in
    node-api)
      cat > package.json << EOF
{
  "name": "$project_name",
  "version": "1.0.0",
  "description": "$description",
  "main": "src/index.js",
  "scripts": {
    "start": "node src/index.js",
    "dev": "nodemon src/index.js",
    "test": "jest"
  },
  "dependencies": {
    "express": "^4.18.0",
    "cors": "^2.8.5",
    "helmet": "^7.0.0",
    "dotenv": "^16.0.0"
  },
  "devDependencies": {
    "nodemon": "^3.0.0",
    "jest": "^29.0.0"
  }
}
EOF
      mkdir -p src
      cat > src/index.js << 'EOF'
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
require('dotenv').config();

const app = express();
app.use(cors());
app.use(helmet());
app.use(express.json());

app.get('/', (req, res) => res.json({ status: 'ok', message: 'API running' }));
app.get('/health', (req, res) => res.json({ uptime: process.uptime() }));

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
EOF
      ;;

    react-app)
      cat > package.json << EOF
{
  "name": "$project_name",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.0.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.0.0",
    "vite": "^5.0.0"
  }
}
EOF
      mkdir -p src public
      cat > src/App.jsx << 'EOF'
import { useState } from 'react';

function App() {
  const [count, setCount] = useState(0);
  return (
    <div style={{ textAlign: 'center', padding: '50px' }}>
      <h1>🚀 App Ready</h1>
      <button onClick={() => setCount(c => c + 1)}>Count: {count}</button>
    </div>
  );
}
export default App;
EOF
      cat > index.html << 'EOF'
<!DOCTYPE html>
<html><head><title>App</title></head>
<body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body>
</html>
EOF
      ;;

    static-site)
      cat > index.html << EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$project_name</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header><h1>🚀 $project_name</h1></header>
  <main><p>$description</p></main>
  <script src="script.js"></script>
</body>
</html>
EOF
      cat > style.css << 'EOF'
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: system-ui; min-height: 100vh; display: flex; flex-direction: column; }
header { background: #667eea; color: white; padding: 2rem; text-align: center; }
main { flex: 1; display: flex; align-items: center; justify-content: center; padding: 2rem; }
EOF
      echo 'console.log("Ready!");' > script.js
      ;;

    python-api)
      cat > main.py << 'EOF'
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="API", version="1.0.0")

class Health(BaseModel):
    status: str
    version: str

@app.get("/")
async def root():
    return {"message": "API running"}

@app.get("/health", response_model=Health)
async def health():
    return Health(status="ok", version="1.0.0")
EOF
      cat > requirements.txt << 'EOF'
fastapi>=0.100.0
uvicorn>=0.23.0
pydantic>=2.0.0
EOF
      ;;

    ai-chatbot)
      cat > package.json << EOF
{
  "name": "$project_name",
  "version": "1.0.0",
  "scripts": { "start": "node src/index.js", "dev": "nodemon src/index.js" },
  "dependencies": { "express": "^4.18.0", "node-fetch": "^3.0.0", "dotenv": "^16.0.0" }
}
EOF
      mkdir -p src
      cat > src/index.js << 'EOF'
const express = require('express');
require('dotenv').config();

const app = express();
app.use(express.json());

const PROVIDERS = {
  groq: { url: 'https://api.groq.com/openai/v1/chat/completions', key: process.env.GROQ_API_KEY },
  together: { url: 'https://api.together.xyz/v1/chat/completions', key: process.env.TOGETHER_API_KEY },
  openrouter: { url: 'https://openrouter.ai/api/v1/chat/completions', key: process.env.OPENROUTER_API_KEY },
  mistral: { url: 'https://api.mistral.ai/v1/chat/completions', key: process.env.MISTRAL_API_KEY },
};

app.post('/chat', async (req, res) => {
  const { message, provider = 'groq', model = 'llama3-8b-8192' } = req.body;
  const p = PROVIDERS[provider];
  if (!p || !p.key) return res.status(400).json({ error: 'Provider not configured' });

  const response = await fetch(p.url, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${p.key}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ model, messages: [{ role: 'user', content: message }] })
  });
  const data = await response.json();
  res.json(data);
});

app.get('/providers', (req, res) => {
  const available = Object.entries(PROVIDERS)
    .filter(([_, p]) => p.key)
    .map(([name]) => name);
  res.json({ providers: available });
});

app.listen(process.env.PORT || 3000, () => console.log('Chatbot API ready'));
EOF
      cat > .env.example << 'EOF'
GROQ_API_KEY=your_key_here
TOGETHER_API_KEY=your_key_here
OPENROUTER_API_KEY=your_key_here
MISTRAL_API_KEY=your_key_here
PORT=3000
EOF
      ;;

    *)
      log WARN "Unknown template: $template_id. Creating basic project."
      echo "# $project_name\n$description" > README.md
      ;;
  esac

  # Always add README
  cat > README.md << EOF
# $project_name

$description

## Quick Start

\`\`\`bash
npm install  # or pip install -r requirements.txt
npm run dev  # or python main.py
\`\`\`

## Auto-generated by Repo Builder 🏗️
EOF

  cd ..
  log INFO "✅ Scaffolded: $project_name"
}

# ═══════════════════════════════════════════════════════
# Auto-Create GitHub Repos
# ═══════════════════════════════════════════════════════
auto_create_repos() {
  log INFO "Checking for repos to create..."

  # Check if we have a project ideas file
  if [ -f ".github/project-ideas.json" ]; then
    python3 -c "
import json, subprocess, sys

with open('.github/project-ideas.json') as f:
    ideas = json.load(f)

for idea in ideas.get('pending', []):
    name = idea['name']
    desc = idea.get('description', '')
    template = idea.get('template', 'static-site')
    private = idea.get('private', False)

    # Check if repo exists
    result = subprocess.run(['gh', 'repo', 'view', name], capture_output=True)
    if result.returncode != 0:
        visibility = '--private' if private else '--public'
        subprocess.run(['gh', 'repo', 'create', name, visibility, '-d', desc, '--clone'])
        print(f'Created: {name}')
    else:
        print(f'Exists: {name}')

# Move to completed
if 'completed' not in ideas:
    ideas['completed'] = []
ideas['completed'].extend(ideas.get('pending', []))
ideas['pending'] = []

with open('.github/project-ideas.json', 'w') as f:
    json.dump(ideas, f, indent=2)
" 2>/dev/null || log INFO "No pending projects to create"
  fi
}

# ═══════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════

# Create template index
create_template_index

# Auto-create repos if configured
auto_create_repos

# Generate report
cat > "$REPORT" << EOF
# 🏗️ Repo Builder Report

**Date:** $(date -u '+%Y-%m-%d %H:%M UTC')

## Templates Available
$(cat "$TEMPLATES_DIR/index.json" 2>/dev/null | jq -r '.templates[] | "- **\(.name)** (\(.id)): \(.description)"' 2>/dev/null || echo "- Template index created")

## Pending Projects
$(if [ -f ".github/project-ideas.json" ]; then
  cat ".github/project-ideas.json" | jq -r '.pending[] | "- \(.name): \(.description)"' 2>/dev/null || echo "None"
else
  echo "None — add projects to .github/project-ideas.json to auto-create them"
fi)

## Usage

Add project ideas to \`.github/project-ideas.json\`:
\`\`\`json
{
  "pending": [
    {
      "name": "my-new-app",
      "description": "A cool new app",
      "template": "react-app",
      "private": false
    }
  ]
}
\`\`\`

---
_Automated by Repo Builder 🏗️_
EOF

cat "$REPORT"
log INFO "🏗️ Repo Builder complete!"
